language: php

php:
    # We only specify one version so we only get one worker
    - 5.3
    - 5.4
    - 5.5

before_script:
    - phpize && ./configure && make && sudo make install
    - echo "extension=aop.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
